"""
CloudSentinel Alert Manager

Responsible for converting security events into alerts
and storing them in the CloudSentinel database.
"""

from src.data.database import save_alert


class AlertManager:
    """
    Manage security alerts generated by CloudSentinel.
    """

    def __init__(self):
        self.alert_count = 0

    def create_alert(self, event):
        """
        Create an alert from a security event.

        Supports both dictionary-based events and
        SecurityEvent-style objects.
        """

        if isinstance(event, dict):
            event_type = event.get("event_type", "UNKNOWN")
            severity = event.get("severity", "INFO")
            message = event.get("message", "No message")
            ip_address = event.get("ip_address", "N/A")

        else:
            event_type = getattr(event, "event_type", "UNKNOWN")
            severity = getattr(event, "severity", "INFO")
            message = getattr(event, "message", "No message")
            ip_address = getattr(event, "ip_address", "N/A")

        alert = {
            "event_type": event_type,
            "severity": severity,
            "message": message,
            "ip_address": ip_address,
        }

        return alert

    def process_alert(self, event):
        """
        Create an alert and save it to the database.
        """

        alert = self.create_alert(event)

        save_alert(alert)

        self.alert_count += 1

        return alert

    def process_event(self, event):
        """
        Backward-compatible method.

        Older parts of CloudSentinel may call process_event().
        """

        return self.process_alert(event)


# ---------------------------------------------------------
# Global Alert Manager
# ---------------------------------------------------------

manager = AlertManager()


# ---------------------------------------------------------
# Public Functions
# ---------------------------------------------------------

def process_alert(event):
    """
    Process a security event and create/save an alert.
    """

    return manager.process_alert(event)


def process_event(event):
    """
    Backward-compatible wrapper for process_alert().
    """

    return manager.process_event(event)


# ---------------------------------------------------------
# Test
# ---------------------------------------------------------

if __name__ == "__main__":

    print("=" * 60)
    print("          CloudSentinel Alert Manager Test")
    print("=" * 60)

    test_event = {
        "event_type": "BRUTE_FORCE",
        "severity": "HIGH",
        "message": (
            "Brute-force attack detected from "
            "192.168.1.50: 5 failed attempts"
        ),
        "ip_address": "192.168.1.50",
    }

    print()
    print("[STEP 1] Creating alert...")

    try:
        alert = manager.create_alert(test_event)

        print("[OK] Alert created.")
        print()
        print("Alert details:")
        print(f"Event Type : {alert['event_type']}")
        print(f"Severity   : {alert['severity']}")
        print(f"Message    : {alert['message']}")
        print(f"IP Address : {alert['ip_address']}")

        print()
        print("[STEP 2] Saving alert to database...")

        saved_alert = manager.process_alert(test_event)

        print("[OK] Alert saved.")
        print()
        print("=" * 60)
        print("          Alert Manager Test Completed")
        print("=" * 60)

    except Exception as error:
        print()
        print("[ERROR] Alert Manager test failed.")
        print(f"Reason: {error}")
