"""
CloudSentinel Alert Manager

Responsible for converting security events into alerts
and storing them in the CloudSentinel database.
"""

from src.data.database import save_alert
from src.notification_manager import send_notification


class AlertManager:
    """
    Manage security alerts generated by CloudSentinel.
    """

    def __init__(self):
        self.alert_count = 0

    def create_alert(self, event):
        """
        Create an alert from a security event.

        Supports both dictionary-based events and
        SecurityEvent-style objects.
        """

        if isinstance(event, dict):
            event_type = event.get("event_type", "UNKNOWN")
            severity = event.get("severity", "INFO")
            message = event.get("message", "No message")
            ip_address = event.get("ip_address", "N/A")

        else:
            event_type = getattr(event, "event_type", "UNKNOWN")
            severity = getattr(event, "severity", "INFO")
            message = getattr(event, "message", "No message")
            ip_address = getattr(event, "ip_address", "N/A")

        alert = {
            "event_type": event_type,
            "severity": severity,
            "message": message,
            "ip_address": ip_address,
        }

        return alert

    def process_alert(self, event):
        """
        Create an alert, save it to the database,
        and send a notification.
        """

        alert = self.create_alert(event)

        save_alert(alert)

        self.alert_count += 1

        send_notification(alert)

        return alert

    def process_event(self, event):
        """
        Process a security event and generate an alert.
        """

        return self.process_alert(event)


# Global AlertManager instance
manager = AlertManager()


def process_alert(event):
    """
    Process a security event and create/save an alert.
    """

    return manager.process_alert(event)


def process_event(event):
    """
    Backward-compatible wrapper for process_alert().
    """

    return manager.process_event(event)


if __name__ == "__main__":

    print("=" * 60)
    print("CloudSentinel Alert Manager Test")
    print("=" * 60)

    test_event = {
        "event_type": "BRUTE_FORCE",
        "severity": "HIGH",
        "message": "Multiple failed login attempts detected",
        "ip_address": "192.168.1.100",
    }

    print("\n[STEP 1] Creating alert...")

    alert = manager.create_alert(test_event)

    print(f"Event Type : {alert['event_type']}")
    print(f"Severity   : {alert['severity']}")
    print(f"Message    : {alert['message']}")
    print(f"IP Address : {alert['ip_address']}")

    print("\n[STEP 2] Saving alert and sending notification...")

    saved_alert = manager.process_alert(test_event)

    print("\n[STEP 3] Alert processed successfully.")
    print(f"Total Alerts Processed: {manager.alert_count}")

    print("\n" + "=" * 60)
